mybatis.configuration.mapUnderscoreToCamelCase: true
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: INFO

spring:
  profiles:
    active: "staging"

---
spring:
  profiles: staging
  datasources:
    blog:
      jdbc-url: jdbc:mysql://127.0.0.1/blog_test?useSSL=false
      username: root
      password: Trydiff12@
      driver-class-name: com.mysql.jdbc.Driver

---
spring:
  profiles: prod
  datasources:
    blog:
      jdbc-url: jdbc:mysql://127.0.0.1/blog?useSSL=false
      username: root
      password: Trydiff12@
      driver-class-name: com.mysql.jdbc.Driver
